import React from 'react'
import Head from 'next/head'
import Cards from '../components/Cards/Cards.jsx'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Por acá veras una navBar con un buscador y botones para hacer el logIn y SignUp</h3>
      <h1>Este es la Home de Let{"'"}s eat!</h1>
      <h1>BIENVENIDOS/AS!!</h1>
      <h3>Imagina que por acá hay filtros</h3>
      <Cards/>

      <h5>Todo se verá hermoso!</h5>
    </div>
  )
}
