import React from 'react'
import Head from 'next/head'
import Cards from '../components/Cards/Cards.jsx'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer/Footer.jsx'
import Filters from '../components/Filters/Filters.jsx'
import NavBar from '../components/NavBar/NavBar.jsx'

export default function Home () {
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Filters/>
      <NavBar/>
      <Footer/>
      <Cards/>

    </div>
  )
}
